apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 60m
  url: https://github.com/kubernetes/ingress-nginx
  ref:
    branch: main
  ignore: |
    /*
    !/deploy
    /deploy/**/.yamllint.yaml
  
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 15m
  path: "./deploy/static/provider/kind"
  prune: false
  sourceRef:
    kind: GitRepository
    name: ingress-nginx