apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-community
  namespace: monitoring
spec:
  interval: 5m
  install:
    timeout: 10m
  chart:
    spec:
      chart: prometheus-community/prometheus
      version: 15.18.0 
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: prometheus-values