apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 5m
  install:
    timeout: 10m
    remediation:
      retries: 3
    crds: Create
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: cert-manager
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: cert-manager
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: cert-manager-values