apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-community
  namespace: monitoring
spec:
  interval: 5m
  install:
    timeout: 10m
    remediation:
      retries: 3
    crds: Create
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: cert-manager
      version: "41.x"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: cert-manager-values